name = "siddhant-site"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Bindings
[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "043fb07a215d4cefa8ee0234f0c78c8e"
